import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import fs from 'fs';
import path from 'path';
import GlobalLayout from "@/components/layout/GlobalLayout";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // Read data from data.json
  const filePath = path.join(process.cwd(), 'components', 'data', 'data.json');
  const fileContents = fs.readFileSync(filePath, 'utf8');
  const fullData = JSON.parse(fileContents);
  
  const common = fullData.common || {};
  const headerData = common.Header;
  const topbarData = common.Topbar;
  const footerData = common.Footer;

  const banners: Record<string, { title: string; backgroundImage: string }> = {};
  
  // Extract all page banners mapping
  if (fullData.sections) {
    if (fullData.sections.AboutHero) banners["about"] = fullData.sections.AboutHero.variants["variant-1"];
    if (fullData.sections.AwardsHero) banners["awards"] = fullData.sections.AwardsHero.variants["variant-1"];
    if (fullData.sections.MissionVisionHero) banners["mission-vision"] = fullData.sections.MissionVisionHero.variants["variant-1"];
    if (fullData.sections.WhyChooseUsHero) banners["why-choose-us"] = fullData.sections.WhyChooseUsHero.variants["variant-1"];
    if (fullData.sections.OurTeamHero) banners["our-team"] = fullData.sections.OurTeamHero.variants["variant-1"];
    if (fullData.sections.TeamDetailHero) banners["team-detail"] = fullData.sections.TeamDetailHero.variants["variant-1"];
    if (fullData.sections.ServicesHero) banners["services"] = fullData.sections.ServicesHero.variants["variant-1"];
    if (fullData.sections.ServiceDetail) banners["service-detail"] = fullData.sections.ServiceDetail.variants["variant-1"].hero;
    if (fullData.sections.PackagesHero) banners["packages"] = fullData.sections.PackagesHero.variants["variant-1"];
  }

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">
        <GlobalLayout
          headerData={headerData}
          topbarData={topbarData}
          footerData={footerData}
          banners={banners}
        >
          {children}
        </GlobalLayout>
      </body>
    </html>
  );
}
