import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import GlobalLayout from "@/components/layout/GlobalLayout";
import { getAppData } from "@/components/lib/getAppData";
import type { PackagesHeroData } from "@/components/types";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const fullData = getAppData();
  const headerData = fullData.common.Header;
  const topbarData = fullData.common.Topbar;
  const footerData = fullData.common.Footer;
  const { sections } = fullData;

  const banners: Record<string, PackagesHeroData> = {
    about: sections.AboutHero.variants["variant-1"],
    awards: sections.AwardsHero.variants["variant-1"],
    "mission-vision": sections.MissionVisionHero.variants["variant-1"],
    "why-choose-us": sections.WhyChooseUsHero.variants["variant-1"],
    "our-team": sections.OurTeamHero.variants["variant-1"],
    "team-detail": sections.TeamDetailHero.variants["variant-1"],
    services: sections.ServicesHero.variants["variant-1"],
    "service-detail": sections.ServiceDetail.variants["variant-1"].hero,
    packages: sections.PackagesHero.variants["variant-1"],
    destinations: sections.DestinationsHero.variants["variant-1"],
    gallery: sections.GalleryHero.variants["variant-1"],
    testimonials: sections.TestimonialsHero.variants["variant-1"],
    faqs: sections.FaqHero.variants["variant-1"],
    blog: sections.BlogHero.variants["variant-1"],
    "blog-detail": sections.BlogDetailHero.variants["variant-1"],
    "package-detail": sections.PackageDetailHero.variants["variant-1"],
    contact: sections.ContactHero?.variants["variant-1"],
    partners: sections.PartnersHero?.variants["variant-1"],
    enquiry: sections.EnquiryHero?.variants["variant-1"],
  };

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">
        <GlobalLayout
          headerData={headerData}
          topbarData={topbarData}
          footerData={footerData}
          banners={banners}
        >
          {children}
        </GlobalLayout>
      </body>
    </html>
  );
}
